name: Push Changes to GitHub

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger this on

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Make Changes
      run: |
        echo "New content" > newfile.txt
        git config user.name "Your Name"
        git config user.email "youremail@example.com"
        git add .
        git commit -m "Add newfile.txt"
        git push

    - name: Push to GitHub
      uses: ad-m/github-push-action@main  # Use a GitHub Actions action to push the changes
      with:
        branch: main  # Replace with the branch you want to push to
        github_token: ${{ secrets.PAC }}  # Use the built-in GitHub token

